### ISSUE TITLE
[2.0] Rewrite publish workflow for SecurityContext removal

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/core-bundle#170]
The 2.0 version, which should aim to support Symfony 2.8 and 3.x, has to be updated for the split of SecurityContext in TokenStorage and AuthorizationChecker.

**Comment by dbu** [comment]
with #183 this should now be pretty straightforward.

**Comment by WouterJ** [comment]
@dbu see https://github.com/symfony-cmf/CoreBundle/pull/181 (not rebased after the merge, but it shows what's needed for Symfony 3 support)

**Comment by WouterJ** [comment]
Done by #181
