### ISSUE TITLE
Doctrine is not available

### ISSUE THREAD

**Issue by michalmarcinkowski** [symfony-cmf/core-bundle#192]
On Sylius we've got an issue 
`An exception has been thrown during the rendering of a template ("Doctrine is not available.")`
More details on [Sylius](https://github.com/Sylius/Sylius/issues/4716) and [stackoverflow](http://stackoverflow.com/questions/36404596/sylius-error-after-composer-update-on-sylius-0-17).

Probably introduced by https://github.com/symfony-cmf/core-bundle/commit/d47ac0f193139a90ecece20c46f42e588213824e and a proposed fix from @Niiko is [here](https://github.com/Sylius/Sylius/issues/4716#issuecomment-206865930). Is that a proper fix or there is other way to fix this?

**Comment by dbu** [comment]
yes, we made it possible to control whether doctrine phpcr-odm is enabled or not, and you need to enable what you want to have. you can either do that on specific bundles, or on the cmf core bundle which prepends this for all other cmf bundles.

**Comment by michalmarcinkowski** [comment]
Ok, we enabled it on cmf core [here](https://github.com/Sylius/Sylius/pull/4834/files) and it works fine. Thanks for the answer!
