### ISSUE TITLE
Fix Symfony 3 builds on master

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/core-bundle#205]
the builds for php 7 currently fail. it looks like composer ends up trying to use phpcr-utils 1.1 which don't support symfony 3. no idea why, however. there is a bunch of tagged phpcr-utils 1.2 that do support symfony 3 (console component). @wouterj do you have an idea?

**Comment by wouterj** [comment]
Fixed by https://github.com/symfony-cmf/core-bundle/commit/95190fda161b5dbff78da4cfbdf0dccbbf5eadd9
