### ISSUE TITLE
Release 1.3.2

### ISSUE THREAD

**Issue by EmmanuelVella** [symfony-cmf/core-bundle#229]
Hi there !

Could you please release a 1.3.2 version ? The [latest fix](https://github.com/symfony-cmf/core-bundle/commit/5a54ca02dc5e8fb473ab86999e9ddacb9dcbee4f) is 3 months old (and I really need it).

Thank you !

**Comment by dbu** [comment]
oops, yep we should have released that. just did https://github.com/symfony-cmf/core-bundle/releases/tag/1.3.2

2.0.0 is out by the way, but we did not talk about it a lot yet because we have a few components not yet on 2.0 and doc needs some more cleanup...

**Comment by EmmanuelVella** [comment]
Thank you very much for the release David ! Can't wait for 2.0 !
