### ISSUE TITLE
publish_workflow  enabled by default means requiring routing-bundle

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/core-bundle#232]
On my tests to install each bundle as separate on a symfony/skeleton app i realized that this bundle misses one dependency. The `symfony/routing-bundle`. `publisch_workflow` enabled means `request_listener` is set, which requires `DynamicRouter` to exist. That chain makes the routing-bundle to be a hard depency. You can see it when doing a `compoer require symfony-cmf/core-bundle` on an empty symfony app.

**Comment by ElectricMaxxx** [comment]
And ... i will let it here to fix it at once:

```
if ($config['persistence']['phpcr']) {
```
in extensions prepend method enables each phpcr implementation of othe cmf bundles, even when `enabled` is false

**Comment by ElectricMaxxx** [comment]
I tried in #233 to require routing-bundle directly. And that isn't a good idea too. This change nothing. the problem is that core-bundle's configuration preparement enables routing-bundle's dynamic router by default, which causes the requirement on one of the persistence. 
So this one could be our first BC problem we have, we should not eable it by default, just on existence of routing-bundle and on of the persistences.

**Comment by ElectricMaxxx** [comment]
@dbu i understand you right, that you whanted to do this issue by disabling the the request_listener by default, right?

**Comment by dbu** [comment]
i propose to change it to the true|false|'auto' pattern we also use elsewhere. see #235
