### ISSUE TITLE
add an install command

### ISSUE THREAD

**Issue by lsmith77** [symfony-cmf/core-bundle#84]
take inspiration from https://github.com/Sylius/SyliusInstallerBundle/blob/master/Command/InstallCommand.php

**Comment by lsmith77** [comment]
another stretch goal for 1.3

**Comment by WouterJ** [comment]
Let's make this a nicetohave. I think this can be quite nice, but maybe more as a standalone CmfSetupBundle/CmfDistributionBundle.

**Comment by dbu** [comment]
i removed the milestone. i don't think its a trivial thing, and indeed fits better in some separate bundle. not everybody will want this in their project.

**Comment by dbu** [comment]
something can be done with flex.

also, we stopped maintaining several of the components, so a cross-bundle installer is less important now.
